### ISSUE TITLE
Image select does not work with other ADCs on the page

### ISSUE THREAD

**Issue by ValoursNet** [AskiaADX/ImageSelect#1]
Not fully tested, but reported a few times

**Comment by FlagBenett** [comment]
The problem I was able to test was regarding the "Force Response size" parameter of the control, in the "Responses" category.
It seems that the width, or height that is selected will then be applied to all controls of the page, rather than just the ADC instance.

This is most likely due to the fact that the responses carry the "class=responseItem", and that "./resources/static/imageSelect.js : line 194" seems to be fetching all items with class=responseItem in the document and then applying the forced width/height.

Here is the effect : 
![adc_image0](https://cloud.githubusercontent.com/assets/11921176/7318257/151fb2c2-ea8a-11e4-82f4-3df6aec898f8.png)

![adc_image](https://cloud.githubusercontent.com/assets/11921176/7318259/1c05ac0e-ea8a-11e4-9331-b62b93347478.png)
